#
# Format
# Channel name:
#   - shutter: number representing the turret position (defined in mmc cfg file)
#     626 nm wavelenght: intensity (0-100)
#     385 nm wavelenght: intensity (0-100)
#     565 nm wavelenght: intensity (0-100)
#     490 nm wavelenght: intensity (0-100)
#
BFF: 
  - shutter: 0
    1: 0
    2: 0
    3: 50
    4: 0
DAP: 
  - shutter: 0
    1: 0
    2: 0
    3: 0
    4: 20
GFP: 
  - shutter: 0
    1: 0
    2: 0
    3: 50
    4: 0
TXR: 
  - shutter: 0
    1: 0
    2: 0
    3: 50
    4: 0
CY5: 
  - shutter: 0
    1: 0
    2: 0
    3: 50
    4: 0